import { useState, useEffect, useRef, Fragment } from "react";
import { useNavigate } from "react-router-dom";
import { API_URL, getToken } from "../utils/api";
import { warna, font } from "../styles/theme";
import logoHorizontal from "../assets/logo-horizontal.png";
import logo from "../assets/logo.png";
import AdminIzin from "./AdminIzin";
import PengaturanGaji from "./PengaturanGaji";
import AdminGajiMassal from "./AdminGajiMassal";
import { labelStatusKehadiran } from "../utils/statusKehadiran";
import { ClipboardList, Clock, Users, FileEdit, Wallet, Building2, BarChart3, ThumbsUp, ArrowRight, CheckCircle2, MapPin, Info, AlertTriangle, Settings, Save, Navigation, FileText, UserX, Bell, UserPlus, FileCheck2, X } from "lucide-react";
